id: I0FDF1A12
ocr_import_info:
  timestamp: '2023-07-28T08:35:25.303023+00:00'
  batch_id: batch-933e
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: bo-t-i0-handwrit
  software_id: ocr-pipelines@v0.1.11
  sponsor: DS
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-07-28 08:41:09.060886+00:00
last_modified: 2023-07-28 08:41:09.060897+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ7858
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ7858
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཡོན་ཏན་མཐའ་ཡས།
  languages:
  - bo
  author: འབྲུག་རྗེ་མཁན་པོ ༡༣་ཡོན་ཏན་མཐའ་ཡས།
statistics:
  ocr_word_mean_confidence_index: 0.34092029866068463
  ocr_word_median_confidence_index: 0.31588371000000004
bases:
  I1KG2836:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2836
      total_pages: 648
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG2836.txt
    statistics:
      ocr_word_median_confidence_index: 0.3175227
      ocr_word_mean_confidence_index: 0.3415206483898935
  I1KG2837:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2837
      total_pages: 552
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG2837.txt
    statistics:
      ocr_word_median_confidence_index: 0.31399065
      ocr_word_mean_confidence_index: 0.3401601485749085
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
